<?php

/**
 * Implements hook_admin_menu_output_alter().
 */
function admin_menu_toggle_admin_menu_output_alter(&$content) {
  if (variable_get('admin_menu_toggle_on', TRUE)) {
    $content['#prefix'] = str_replace('<div id="admin-menu-wrapper">',
      '<div id="admin-menu-toggle" class="toggle-hide">[T]</div><div id="admin-menu-wrapper">',
      $content['#prefix']);
  }
}

/**
 * Implements hook_form_FORM_alter().
 */
function admin_menu_toggle_form_admin_menu_theme_settings_alter(&$form, &$form_state, $form_id) {
  $form['toggle'] = array(
    '#type' => 'fieldset',
    '#title' => t('Toggle'),
    '#group' => 'advanced',
  );
  $form['toggle']['admin_menu_toggle_on'] = array(
    '#type' => 'checkbox',
    '#title' => t('Turn on'),
    '#default_value' => variable_get('admin_menu_toggle_on', TRUE),
  );
}
